collections:
  - name: "Projects",
  - folder: "src/pages/projects"
  - fields:
      - label: "Title",
        name: "title"
        widget: "string"
      - label: "Publish Date",
        name: "date"
        widget: "datetime"
      - label: "Body",
        name: "body"
        widget: "markdown"
